import { TabWidget } from "std-widgets.slint";
import { Theme } from "../theme.slint";
import { Routers } from "../routers.slint";

export component CreatePage inherits Window {
  callback continue(Routers);

    HorizontalLayout {
        alignment: center;
        height: Theme.app-height;
        width: Theme.app-width;

        VerticalLayout {
            alignment: center;
            TabWidget {
                Tab {
                    title: @tr("Login");
                    
                }
                Tab {
                    title: @tr("Login");
                }
            }
        }
    }
}
