import { Theme } from "../theme.slint";
import { Routers } from "../routers.slint";

export component CreatePage inherits Window {
  callback continue(Routers);

    HorizontalLayout {
        VerticalLayout {
            height: Theme.app-height;
            Image {
                source: @image-url("../images/zebra_print.png");
                colorize: Theme.window-background-inverse;
                height: 100%;
                width: Theme.zerba-print-length;
                image-fit: fill;
            }
        }
        VerticalLayout {
            alignment: center;
        }
    }
}
