import { Theme } from "../theme.slint";
import { Routers } from "../routers.slint";
import { TopBar } from "../components/topbar.slint";
import { LeftBar, SubHomeRoute } from "../components/leftbar.slint";
import {
    SubPageManage,
    SubPagePassgen,
    SubPageSettings
} from "../sub-page/pages.slint";


export component HomePage inherits Window {
    private property <SubHomeRoute> route;

    callback continue(Routers);

    HorizontalLayout {
        LeftBar {
            route <=> route;
        }
        VerticalLayout {
            height: Theme.app-height;
            TopBar {}
            if route == SubHomeRoute.Manage: SubPageManage {
                
            }
            if route == SubHomeRoute.PasswordGen: SubPagePassgen {
                
            }
            if route == SubHomeRoute.Settings: SubPageSettings {
                
            }
        }
    }
}
