import { Theme } from "../theme.slint";
import { Routers } from "../routers.slint";
import { TopBar } from "../components/topbar.slint";
import { LeftBar, SubHomeRoute } from "../components/leftbar.slint";
import {
    SubPageManage,
    SubPagePassgen,
    SubPageSettings
} from "../sub-page/pages.slint";

export component HomePage inherits Window {
    private property <SubHomeRoute> route : SubHomeRoute.PasswordGen;
    private property <string> top-bar-title;

    callback continue(Routers);

    states []

    HorizontalLayout {
        LeftBar {
            route <=> route;
        }
        if route == SubHomeRoute.Manage: SubPageManage {
                
        }
        if route == SubHomeRoute.PasswordGen: SubPagePassgen {
            
        }
        if route == SubHomeRoute.Settings: SubPageSettings {
            
        }
    }
}
