import { Theme } from "../theme.slint";
import { Routers } from "../routers.slint";
import { LeftBar, SubHomeRoute } from "../components/leftbar.slint";
import {
    SubPageManage,
    SubPagePassgen,
    SubPageSettings,
    AddEditPageManage
} from "../sub-page/pages.slint";

export component HomePage inherits Window {
    private property <SubHomeRoute> last-route : SubHomeRoute.Manage;
    private property <SubHomeRoute> route : SubHomeRoute.AddEdit;
    private property <string> top-bar-title;

    callback continue(Routers);

    states []

    HorizontalLayout {
        LeftBar {
            route <=> route;
        }
        if route == SubHomeRoute.Manage: SubPageManage {
            add-record => {
                last-route = route;
                route = SubHomeRoute.AddEdit;
            }
        }
        if route == SubHomeRoute.AddEdit : AddEditPageManage {
            close => {
                route = last-route;
            }
        }
        if route == SubHomeRoute.PasswordGen: SubPagePassgen {}
        if route == SubHomeRoute.Settings: SubPageSettings {        }
    }
}
