import { StandardListView } from "std-widgets.slint";
import { ZButton } from "../components/button.slint";
import { Theme } from "../theme.slint";
import { Routers } from "../routers.slint";

export component LangChoosePage inherits Window {
    callback continue(Routers);

    HorizontalLayout {
        VerticalLayout {
            height: Theme.app-height;
            Image {
                source: @image-url("../images/zebra_print.png");
                colorize: Theme.window-background-inverse;
                height: 100%;
                width: Theme.zerba-print-length;
                image-fit: fill;
            }
        }
        VerticalLayout {
            height: 100%;
            width: 100%;
            HorizontalLayout {
                alignment: center;
                VerticalLayout {
                    alignment: center;
                    Text {
                        text: @tr("Welcome");
                        font-size: Theme.font-size-medium * 2;
                        horizontal-alignment: center;
                    }
                    StandardListView {
                        height: 300pt;
                        current-item: 0;
                        model: [
                            {
                                text: "English",
                                code: "en",
                                encode: "UTF-8"
                            },
                            {
                                text: "Chinese (Simplified Han, China)",
                                code: "cn",
                                encode: "GB2312"
                            },
                            {
                                text: "Russian",
                                code: "ru",
                                encode: "ISO-8859-5"
                            },
                            {
                                text: "Japanese",
                                code: "ja",
                                encode: "UTF-8"
                            },
                        ];
                    }
                    continue-button := ZButton {
                        height: 36pt;
                        width: 160pt;
                        color: Theme.window-background;
                        background: Theme.window-background-inverse;
                        text: @tr("Continue");
                        clicked => {
                            continue(Routers.Start)
                        }
                    }
                }
            }
        }
    }
}
