import {
    VerticalBox,
    Button,
    ComboBox,
    Slider,
    GridBox,
    GroupBox,
    HorizontalBox,
    StandardListView
} from "std-widgets.slint";
import { ZButton } from "../components/button.slint";
import { ZLabel } from "../components/label.slint";
import { ZComboBox } from "../components/combo_box.slint";
import { ZTag } from "../components/tag.slint";
import { Theme } from "../theme.slint";
import { ZLockIcon, ZHideEyeIcon, ZGearIcon } from "../icons/icons.slint";
import { Routers } from "../routers.slint";

export component LangChoosePage inherits Window {
    callback continue(Routers);

    GridLayout {
        VerticalLayout {
            height: 450pt;
            Image {
                source: @image-url("../images/zebra_print.png");
                colorize: Theme.window-background-inverse;
                height: 100%;
                width: 10%;
                image-fit: fill;
            }
        }
        VerticalLayout {
            height: 100%;
            GridLayout {
                VerticalBox {
                    alignment: center;

                    GroupBox {
                        width: 20%;
                        vertical-stretch: 0;

                        HorizontalBox {
                            alignment: end;

                            VerticalBox {
                                alignment: center;
                                padding: 0px;
    
                                Text {
                                    text: @tr("Welcome");
                                    font-size: Theme.font-size-medium * 2;
                                    horizontal-alignment: center;
                                }
                                StandardListView {
                                    height: 300pt;
                                    model: [
                                        {
                                            text: "Chinese (Simplified Han, China)",
                                            code: "cn",
                                            encode: "GB2312"
                                        },
                                        {
                                            text: "English",
                                            code: "en",
                                            encode: "UTF-8"
                                        },
                                        {
                                            text: "Russian",
                                            code: "ru",
                                            encode: "ISO-8859-5"
                                        },
                                        {
                                            text: "Japanese",
                                            code: "ja",
                                            encode: "UTF-8"
                                        },
                                    ];
                                }
                                continue-button := ZButton {
                                    height: 36pt;
                                    width: 160pt;
                                    color: Theme.window-background;
                                    background: Theme.window-background-inverse;
                                    text: @tr("Continue");
                                    clicked => {
                                        continue(Routers.Start)
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
