import { StandardListView } from "std-widgets.slint";
import { ZButton } from "../components/button.slint";
import { Theme } from "../theme.slint";
import { Routers } from "../routers.slint";
import { SettingsLogic } from "../logic.slint";

export component LangChoosePage inherits Window {
    private property <int> lang_index : 0;
    private property <[string]> codes : ["en", "cn", "ru", "ja"];
    private property <[StandardListViewItem]> models : [
        {
            text: "English",
            code: "en",
        },
        {
            text: "Chinese (Simplified Han, China)",
            code: "cn",
        },
        {
            text: "Russian",
            code: "ru",
        },
        {
            text: "Japanese",
            code: "ja",
        },
    ];

    callback continue(Routers);

    HorizontalLayout {
        VerticalLayout {
            height: Theme.app-height;
            Image {
                source: @image-url("../images/zebra_print.png");
                colorize: Theme.window-background-inverse;
                height: 100%;
                width: Theme.zerba-print-length;
                image-fit: fill;
            }
        }
        VerticalLayout {
            height: 100%;
            width: 100%;
            HorizontalLayout {
                alignment: center;
                VerticalLayout {
                    alignment: center;
                    Text {
                        text: @tr("Welcome");
                        font-size: Theme.font-size-medium * 2;
                        horizontal-alignment: center;
                    }
                    StandardListView {
                        current-item <=> lang_index;
                        height: 300pt;
                        model: models;
                        item-pointer-event => {
                            SettingsLogic.lang = codes[lang-index];
                        }
                    }
                    continue-button := ZButton {
                        height: 36pt;
                        width: 160pt;
                        color: Theme.window-background;
                        background: Theme.window-background-inverse;
                        text: @tr("Continue");
                        clicked => {
                            continue(Routers.Start);
                        }
                    }
                }
            }
        }
    }
}
