import { ZButton } from "../components/button.slint";
import { Theme } from "../theme.slint";
import { ZInput } from "../components/input.slint";
import { Routers } from "../routers.slint";
import { ZLockIcon } from "../icons/lock.slint";
import { Zlink } from "../components/link.slint";

export component LockPage inherits Window {
    callback continue(Routers);

    HorizontalLayout {
        VerticalLayout {
            height: Theme.app-height;
            Image {
                source: @image-url("../images/zebra_print.png");
                colorize: Theme.window-background-inverse;
                height: 100%;
                width: Theme.zerba-print-length;
                image-fit: fill;
            }
        }
        VerticalLayout {
            width: Theme.app-width - Theme.zerba-print-length;
            alignment: center;
            HorizontalLayout {
                width: 100%;
                alignment: center;
                VerticalLayout {
                    alignment: center;
                    spacing: 5pt;
                    ZLockIcon {
                        height: 40pt;
                        fill: Theme.window-background-inverse;
                    }
                    ZInput {
                        height: 46pt;
                        width: 220pt;
                        alignment: center;
                        placeholder: @tr("Password");
                        label-color: Theme.window-background-inverse.darker(50%);
                    }
                    HorizontalLayout {
                        height: 15pt;
                        Text {
                            horizontal-alignment: center;
                            color: Theme.danger;
                            text: @tr("error");
                        }
                    }
                    ZButton {
                        height: 36pt;
                        width: 220pt;
                        color: Theme.window-background;
                        background: Theme.window-background-inverse;
                        text: @tr("Unlock");
                        clicked => {
                            // continue(Routers.SetupAccount)
                        }
                    }
                    HorizontalLayout {
                        alignment: center;
                        VerticalLayout {
                            padding-right: 2pt;
                            alignment: center;
                            Rectangle {
                                width: 100pt;
                                height: 1pt;
                                background: Theme.window-background-inverse.transparentize(50%);
                            }
                        }
                        Text {
                            text: @tr("Or");
                            color: Theme.window-background-inverse.transparentize(50%);
                        }
                        VerticalLayout {
                            alignment: center;
                            padding-left: 2pt;
                            Rectangle {
                                width: 100pt;
                                height: 1pt;
                                background: Theme.window-background-inverse.transparentize(50%);
                            }
                        }
                    }
                    HorizontalLayout {
                        alignment: center;
                        Zlink {
                            color: Theme.secondary;
                            text: @tr("Restore");
                        }
                    }
                }
            }
        }
    }
}
