import { StandardListView, LineEdit , VerticalBox } from "std-widgets.slint";
import { ZButton } from "../components/button.slint";
import { ZInput } from "../components/input.slint";
import { Zlink } from "../components/link.slint";
import { Theme } from "../theme.slint";
import { Routers } from "../routers.slint";

export component LoginPage inherits Window {
    callback continue(Routers);

    HorizontalLayout {
        VerticalLayout {
            height: Theme.app-height;
            Image {
                source: @image-url("../images/zebra_print.png");
                colorize: Theme.window-background-inverse;
                height: 100%;
                width: Theme.zerba-print-length;
                image-fit: fill;
            }
        }
        VerticalLayout {
            width: Theme.app-width - Theme.zerba-print-length;
            alignment: center;
            HorizontalLayout {
                width: 100%;
                alignment: center;
                Text {
                    text: @tr("Sign in");
                    font-size: Theme.font-size-medium * 2;
                    font-weight: Theme.font-weight-bold;
                    horizontal-alignment: center;
                }
            }
            HorizontalLayout {
                width: 100%;
                padding-top: 15pt;
                alignment: center;
                VerticalLayout {
                    alignment: center;
                    spacing: 10pt;
                    ZInput {
                        alignment: center;
                        height: 46pt;
                        width: 220pt;
                        label: @tr("Username");
                        placeholder: @tr("Enter your Username");
                        label-color: Theme.window-background.darker(50%);
                    }
                    ZInput {
                        height: 46pt;
                        width: 220pt;
                        alignment: center;
                        type: password;
                        label: @tr("Password");
                        placeholder: @tr("Enter your Password");
                        label-color: Theme.window-background.darker(50%);
                    }
                    HorizontalLayout {
                        alignment: start;
                        Zlink {
                            color: Theme.primary;
                            text: @tr("Forgot Password");
                        }
                    }
                    ZButton {
                        height: 36pt;
                        width: 220pt;
                        color: Theme.window-background;
                        background: Theme.window-background-inverse;
                        text: @tr("Sign in");
                        enabled: true;
                        clicked => {
                            // continue(Routers.Login)
                        }
                    }
                    HorizontalLayout {
                        alignment: center;
                        VerticalLayout {
                            padding-right: 2pt;
                            alignment: center;
                            Rectangle {
                                width: 100pt;
                                height: 1pt;
                                background: Theme.window-background-inverse.transparentize(50%);
                            }
                        }
                        Text {
                            text: @tr("Or");
                            color: Theme.window-background-inverse.transparentize(50%);
                        }
                        VerticalLayout {
                            alignment: center;
                            padding-left: 2pt;
                            Rectangle {
                                width: 100pt;
                                height: 1pt;
                                background: Theme.window-background-inverse.transparentize(50%);
                            }
                        }
                    }
                    ZButton {
                        height: 36pt;
                        width: 220pt;
                        color: Theme.window-background-inverse;
                        background: Theme.window-background;
                        border-color: Theme.window-background-inverse;
                        text: @tr("Sign up");
                        enabled: true;
                        hovered: false;
                        clicked => {
                            continue(Routers.Mnemonic)
                        }
                    }
                }
            }
        }
    }
}
