import { StandardListView, LineEdit , VerticalBox} from "std-widgets.slint";
import { ZButton } from "../components/button.slint";
import { ZInput } from "../components/input.slint";
import { Theme } from "../theme.slint";
import { Routers } from "../routers.slint";

export component LoginPage inherits Window {
    callback continue(Routers);

    HorizontalLayout {
        VerticalLayout {
            height: Theme.app-height;
            Image {
                source: @image-url("../images/zebra_print.png");
                colorize: Theme.window-background-inverse;
                height: 100%;
                width: Theme.zerba-print-length;
                image-fit: fill;
            }
        }
        VerticalLayout {
            width: Theme.app-width - Theme.zerba-print-length;
            alignment: center;
            HorizontalLayout {
                width: 100%;
                alignment: center;
                Text {
                    text: @tr("Sign in");
                    font-size: Theme.font-size-medium * 2;
                    font-weight: Theme.font-weight-bold;
                    horizontal-alignment: center;
                }
            }
            HorizontalLayout {
                width: 100%;
                alignment: center;
                VerticalLayout {
                    alignment: center;
                    spacing: 10pt;
                    ZInput {
                        alignment: center;
                        height: 46pt;
                        width: 220pt;
                        label: @tr("Username");
                        label-color: Theme.window-background.darker(50%);
                    }
                    ZInput {
                        height: 46pt;
                        width: 220pt;
                        alignment: center;
                        label: @tr("Password");
                        label-color: Theme.window-background.darker(50%);
                    }
                    // ZButton {}
                }
            }
        }
    }
}
