import { LockPage } from "lock.slint";
import { LangChoosePage } from "lang_choose.slint";
import { StartPage } from "start.slint";
import { MnemonicPage } from "mnemonic.slint";
import { PrivacyPage } from "privacy.slint";
import { LoginPage } from "login.slint";
import { SetupAccountPage } from "setup_account.slint";

export {
  LockPage,
  StartPage,
  LangChoosePage,
  MnemonicPage,
  PrivacyPage,
  LoginPage,
  SetupAccountPage
}
