import { HorizontalBox, TextEdit, CheckBox } from "std-widgets.slint";
import { ZButton } from "../components/button.slint";
import { Theme } from "../theme.slint";
import { Routers } from "../routers.slint";

export component PrivacyPage inherits Window {
    private property <bool> accepted : false;

    callback continue(Routers);

    HorizontalLayout {
        VerticalLayout {
            height: Theme.app-height;
            Image {
                source: @image-url("../images/zebra_print.png");
                colorize: Theme.window-background-inverse;
                height: 100%;
                width: Theme.zerba-print-length;
                image-fit: fill;
            }
        }
        VerticalLayout {
            height: 100%;
            width: 100%;
            HorizontalLayout {
                padding-left: 30pt;
                padding-right: 30pt;
                alignment: center;
                VerticalLayout {
                    alignment: center;
                    spacing: 10pt;
                    Text {
                        text: @tr("Privacy Policy");
                        font-size: Theme.font-size-medium * 2;
                        horizontal-alignment: center;
                    }
                    TextEdit {
                        height: 60%;
                        width: 60%;
                        text: @tr("This is our TextEdit widget, which allows for editing text that spans over multiple paragraphs.\nFor example this line starts in a new paragraph.\n\nWhen the amount of lines - due to wrapping and number of paragraphs - exceeds the available vertical height, a vertical scrollbar is shown that allows scrolling.\nYou may want to enter a bit of text here then in order to make them visible.");
                        wrap: word-wrap;
                        enabled: false;
                    }
                    CheckBox {
                        text: @tr("Accept privacy policy");
                        checked <=> accepted;
                        enabled: true;
                    }
                    HorizontalLayout {
                        alignment: center;
                        ZButton {
                            height: 36pt;
                            width: 160pt;
                            color: Theme.window-background;
                            background: Theme.window-background-inverse;
                            text: @tr("Continue");
                            enabled: accepted;
                            clicked => {
                                continue(Routers.Login)
                            }
                        }
                    }
                }
            }
        }
    }
}
