import { CheckBox } from "std-widgets.slint";
import { Theme } from "../theme.slint";
import { Routers } from "../routers.slint";
import { ZTag } from "../components/tag.slint";
import { ZButton } from "../components/button.slint";
import { ZInput } from "../components/input.slint";
import { KeyChainLogic } from "../logic.slint";


export component SetupAccountPage inherits Window {
    private property <bool> accepted_email : true;

    callback continue(Routers);

    HorizontalLayout {
        VerticalLayout {
            height: Theme.app-height;
            Image {
                source: @image-url("../images/zebra_print.png");
                colorize: Theme.window-background-inverse;
                height: 100%;
                width: Theme.zerba-print-length;
                image-fit: fill;
            }
        }
        VerticalLayout {
            width: Theme.app-width - Theme.zerba-print-length;
            alignment: center;
            HorizontalLayout {
                width: 100%;
                alignment: center;
                padding-bottom: 15pt;
                VerticalLayout {
                    alignment: center;
                    Text {
                        text: @tr("Create a New Account");
                        font-size: Theme.font-size-medium * 2;
                        font-weight: Theme.font-weight-bold;
                        horizontal-alignment: center;
                    }
                    Text {
                        text: @tr("Setup Account parameters");
                        font-size: Theme.font-size-medium;
                        font-weight: Theme.font-weight-bold;
                        horizontal-alignment: center;
                    }
                    HorizontalLayout {
                        alignment: center;
                        padding-top: 10pt;
                        VerticalLayout {
                            ZInput {
                                height: 46pt;
                                width: 220pt;
                                alignment: center;
                                type: password;
                                placeholder: @tr("Enter Master Password");
                                label-color: Theme.window-background-inverse.darker(50%);
                                value <=> KeyChainLogic.password;
                            }
                            ZInput {
                                height: 46pt;
                                width: 220pt;
                                alignment: center;
                                enabled: accepted_email;
                                placeholder: @tr("Email Optional");
                                label-color: Theme.window-background-inverse.darker(50%);
                                value <=> KeyChainLogic.email;
                            }
                            CheckBox {
                                text: @tr("Enable Email (Restore Password)");
                                checked <=> accepted_email;
                                enabled: true;
                            }
                            CheckBox {
                                text: @tr("Enable Sync global server");
                                checked <=> KeyChainLogic.sync;
                                enabled: true;
                            }
                            ZButton {
                                height: 36pt;
                                width: 220pt;
                                color: Theme.window-background-inverse;
                                background: Theme.primary;
                                border-color: Theme.primary;
                                text: @tr("Create");
                                enabled: true;
                                clicked => {}
                            }
                        }
                    }
                }
            }
        }
    }
}
