import { VerticalBox, Button, ComboBox, Slider, GridBox } from "std-widgets.slint";
import { ZButton } from "../components/button.slint";
import { ZLabel } from "../components/label.slint";
import { ZComboBox } from "../components/combo_box.slint";
import { ZTag } from "../components/tag.slint";
import { ZLockIcon, ZHideEyeIcon, ZGearIcon } from "../icons/icons.slint";

import { Routers } from "../routers.slint";
import { Theme } from "../theme.slint";

export component StartPage inherits Window {
    callback continue(Routers);

    GridLayout {
        VerticalLayout {
            height: 450pt;
            Image {
                source: @image-url("../images/zebra_print.png");
                colorize: Theme.window-background-inverse;
                height: 100%;
                width: Theme.zerba-print-length;
                image-fit: fill;
            }
        }
        VerticalLayout {
            height: 100%;
            GridLayout {
                VerticalBox {
                    alignment: center;

                }
            }
        }
    }
}
