import { IconButton } from "../components/icon-btn.slint";
import { Theme } from "../theme.slint";

export component AddElementForm inherits VerticalLayout {
    in property <string> title;

    callback close;

    alignment: start;
    padding: 15pt;
    HorizontalLayout {
        alignment: space-between;
        Text {
            text: root.title;
            font-family: Theme.font-family;
            font-size: Theme.font-size-big;
            font-weight: Theme.font-weight-bold;
            vertical-alignment: center;
        }
        IconButton {
            background: Theme.window-background-inverse;
            hover-color: Theme.secondary;
            source: @image-url("../images/close.svg");
            img-width: 30pt;
            img-height: 30pt;
            clicked => {
                close();
            }
        }
    }
}
