import { HorizontalBox } from "std-widgets.slint";

import { IconButton } from "../components/icon-btn.slint";
import { ZTag } from "../components/tag.slint";
import { Theme } from "../theme.slint";
import { Element } from "../logic.slint";
import { RecordField } from "field.slint";



export component ElementOfItem inherits VerticalLayout {
    in property <int> index : 0;
    in property <Element> data;

    callback edit(int /* index */);
    callback delete(int /* index */);

    alignment: start;
    padding: 10pt;
    padding-left: 20pt;
    padding-right: 20pt;
    width: Theme.app-width - 245pt;
    HorizontalLayout {
        alignment: space-between;
        HorizontalBox {
            IconButton {
                background: Theme.window-background-inverse;
                hover-color: Theme.secondary;
                source: @image-url("../images/edit.svg");
                img-width: 15pt;
                img-height: 15pt;
                text: "edit";
                clicked => {
                    edit(index);
                }
            }
            IconButton {
                background: Theme.window-background-inverse;
                hover-color: Theme.secondary;
                source: @image-url("../images/del.svg");
                img-width: 15pt;
                img-height: 15pt;
                text: "delete";
                clicked => {
                    delete(index);
                }
            }
         }
    }
    VerticalLayout {
        spacing: 5pt;
        padding-top: 15pt;
        HorizontalLayout {
            alignment: center;
            padding-bottom: 10pt;
            Rectangle {
                width: 30pt;
                height: 30pt;
                background: red;
                border-radius: 100pt;
            }
        }
        RecordField {
            height: 40pt;
            background: Theme.primary;
            read-only: true;
            label: @tr("Name");
            value: data.name;
        }
        RecordField {
            height: 40pt;
            background: Theme.primary;
            read-only: true;
            label: @tr("website");
            value: data.website;
        }
    }
    HorizontalLayout {
        padding-top: 10pt;
        padding-bottom: 10pt;
        alignment: center;
        Rectangle {
            height: 1pt;
            width: 70%;
            background: Theme.window-background-inverse.transparentize(50%);
        }
    }
    VerticalLayout {
        spacing: 5pt;
        for field in data.fields : RecordField {
            height: 40pt;
            background: Theme.primary;
            read-only: true;
            label: field.title;
            value: field.value;
            hide: field.hide;
            copy: field.copy;
        }
    }
    if data.extra-fields.length > 0 : HorizontalLayout {
        padding-top: 10pt;
        padding-bottom: 10pt;
        alignment: center;
        Rectangle {
            height: 1pt;
            width: 70%;
            background: Theme.window-background-inverse.transparentize(50%);
        }
    }
    VerticalLayout {
        spacing: 5pt;
        for field in data.extra-fields : RecordField {
            height: 40pt;
            background: Theme.primary;
            read-only: true;
            label: field.title;
            value: field.value;
            hide: field.hide;
            copy: field.copy;
        }
    }
    VerticalLayout {
        padding-top: 10pt;
        HorizontalLayout {
            alignment: end;
            Text {
                text: "Last Modified:";
            }
            Text {
                text: data.updated;
            }
        }
        HorizontalLayout {
            alignment: end;
            Text {
                text: "Created::";
            }
            Text {
                text: data.created;
            }
        }
    }
}

