import { StyleMetrics , Button} from "std-widgets.slint";
import { Theme } from "../theme.slint";

export component IconButton {
    in-out property<bool> enabled : true;
    in-out property <color> hover-color;
    in property <bool> hovered: true;
    in property <string> text;
    in property <color> background;
    in property<image> source;
    in property <length> img-width;
    in property <length> img-height;
    in property <length> font-size;

    callback clicked;

    touch := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            if (root.enabled) {
                clicked();
            }
        }
    }

    HorizontalLayout {
        VerticalLayout {
            alignment: center;
            img := Image {
                source: root.source;
                colorize: root.background;
                width: root.img-width;
                height: root.img-height;
                image-fit: fill;
            }
        }
        VerticalLayout {
            alignment: center;
            txt := Text {
                text: root.text;
                color: root.background;
                font-family: Theme.font-family;
                font-size: root.font-size;
            }
        }
    }

    states [
        active when root.enabled && hovered && touch.has-hover: {
            img.colorize: root.hover-color;
            txt.color: root.hover-color;
            in {
              animate img.colorize { duration: 150ms; }
            }
        }
    ]
}