export component IconWrap {
    in-out property <bool> selected : false;
    in property <color> background;
    
    callback clicked;

    HorizontalLayout {
        alignment: start;
        visible <=> selected;
        Rectangle {
            width: 3pt;
            height: 30pt;
            background: root.background;
        }
    }
    touch := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            clicked();
        }
    }
    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            alignment: center;
            @children
        }
    }
}