import { StyleMetrics , Button} from "std-widgets.slint";
import { Theme } from "../theme.slint";

export component IconButton {
    in-out property<bool> enabled : true;
    in-out property <color> hover-color;
    in property <bool> hovered: true;
    in property <string> text;
    in property <color> background;
    in property<image> source;
    in property <length> img-width;

    callback clicked;

    touch := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            if (root.enabled) {
                clicked();
            }
        }
    }

    img := Image {
        source: root.source;
        colorize: root.background;
        width: root.img-width;
        image-fit: fill;
    }
    states [
        active when root.enabled && hovered && touch.has-hover: {
            img.colorize: root.hover-color;
            in {
              animate img.colorize { duration: 150ms; }
            }
        }
    ]
}