import { StyleMetrics, LineEdit, TextEdit } from "std-widgets.slint";
import { Theme } from "../theme.slint";

export component ZInput inherits VerticalLayout {
    in property <string> label;
    in property <color> label-color;
    in property <InputType> type;
    in property <string> placeholder;
    in-out property<bool> enabled : true;
    in-out property<string> value;

    callback accepted();

    Text {
        text: root.label;
        color: root.label-color;
        font-family: Theme.font-family;
        font-size: Theme.font-size-regular;
    }
    LineEdit {
        height: root.height - 10pt;
        width: root.width;
        input-type: root.type;
        font-size: Theme.font-size-medium;
        placeholder-text: root.placeholder;
        enabled: enabled;
        text <=> value;
        accepted => {
            accepted();
        }
    }
}
