import { Theme } from "../theme.slint";
import { Element } from "../logic.slint";

export component ItemComponent inherits Rectangle {
    in-out property <Element> data;
    in-out property <bool> selected;

    callback clicked();

    states [
        pressed when root.selected : {
            root.background : Theme.secondary.darker(70%);
            touch.mouse-cursor: default;
        }
    ]

    touch := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            clicked();
        }
    }

    HorizontalLayout {
        padding-left: 30pt;
        spacing: 16pt;
        VerticalLayout {
            alignment: center;
        }
        VerticalLayout {
            alignment: center;
            Text {
                text: data.name;
                font-family: Theme.font-family;
                font-size: 10pt;
                font-weight: Theme.font-weight-bold;
                color: Theme.window-background-inverse;
            }
            Text {
                text: data.website;
                font-family: Theme.font-family;
                font-size: 8pt;
                font-weight: Theme.font-weight-regular;
                color: Theme.secondary;
                height: 10pt;
            }
        }
    }
}
