import { Theme } from "../theme.slint";
import { Button } from "std-widgets.slint";
import { ZLockIcon } from "../icons/lock.slint";
import { ZGearIcon } from "../icons/gear.slint";
import { IconWrap } from "../components/icon-wrap.slint";

export enum SubHomeRoute {
    Manage,
    PasswordGen,
    Settings
}

export component LeftBar inherits Rectangle {
    in-out property <SubHomeRoute> route : SubHomeRoute.Manage;

    background: Theme.window-background-inverse;
    height: Theme.app-height;
    width: 40pt;

    VerticalLayout {
        padding-top: 60pt;
        spacing: 10pt;
        IconWrap {
            selected: route == SubHomeRoute.Manage;
            background: Theme.window-background;
            clicked => {
                if (route != SubHomeRoute.Manage) {
                    route = SubHomeRoute.Manage;
                }
            }
            ZLockIcon {
                fill: Theme.window-background;
                width: 20pt;
                height: 20pt;
            }
        }
        IconWrap {
            selected: route == SubHomeRoute.PasswordGen;
            background: Theme.window-background;
            clicked => {
                if (route != SubHomeRoute.PasswordGen) {
                    route = SubHomeRoute.PasswordGen;
                }
            }
            Image {
                source: @image-url("../images/magic.svg");
                colorize: Theme.window-background;
                width: 20pt;
                height: 20pt;
            }
        }
        IconWrap {
            selected: route == SubHomeRoute.Settings;
            background: Theme.window-background;
            clicked => {
                if (route != SubHomeRoute.Settings) {
                    route = SubHomeRoute.Settings;
                }
            }
            ZGearIcon {
                fill: Theme.window-background;
                width: 20pt;
                height: 20pt;
            }
        }
    }
}