import { Theme } from "../theme.slint";

export component Zlink inherits TouchArea {
    in property <string> text;
    in property <color> color : Theme.window-background-inverse;
    in property <color> hover-color : Theme.primary;
    in property <int> font-weight : Theme.font-weight-regular;
    in property <string> font-family : Theme.font-family;
    in property <length> font-size : Theme.font-size-regular;

    mouse-cursor: pointer;

    txt := Text {
        text: text;
        color: root.color;
        font-family: root.font-family;
        font-weight: root.font-weight;
        font-size: root.font-size;
    }

    states [
        active when root.has-hover: {
            txt.color : root.hover-color;
            in {
              animate txt.color { duration: 150ms; }
            }
        }
    ]
}
