import { ScrollView , VerticalBox} from "std-widgets.slint";

import { IconButton } from "../components/icon-btn.slint";
import { RecordField } from "../components/field.slint";
import { Theme } from "../theme.slint";
import { KeyChainLogic, Element, GeneratorLogic, LogicResult } from "../logic.slint";
import { ZButton } from "./button.slint";
import { PassGenForm } from "../components/pass-gen-form.slint";

export component EditLogin {
    private property <LogicResult> result : GeneratorLogic.request-password-gen(lowercase, upercase, nums, symbols, length);
    private property <bool> lowercase : true;
    private property <bool> upercase : true;
    private property <bool> nums : true;
    private property <bool> symbols : true;
    private property <int> length : 30;

    in property <bool> read-only;
    in property <bool> edit : false;
    in-out property <Element> element : {
        name: "",
        website: "",
        icon: "",
        type: 0,
        favourite: false,
        created: "",
        updated: "",
        fields: [
            {
                title: "Username",
                value: "",
                hide: false,
                copy: false
            },
            {
                title: "Password",
                value: result.response,
                hide: true,
                copy: false
            },
            {
                title: "Authenticator key (TOTP)",
                value: "",
                hide: false,
                copy: false
            },
        ],
        extra_fields: []
    };

    callback save(Element);

    popup := PopupWindow {
        close-on-click: false;

        Rectangle {
            background: Theme.window-background;
            border-color: Theme.window-background-inverse;
            border-width: 2pt;
            border-radius: 8pt;
            padding: 16pt;
        }
        VerticalBox {
            padding: 16pt;
            PassGenForm {
                lowercase <=> lowercase;
                upercase <=> upercase;
                nums <=> nums;
                symbols <=> symbols;
                length <=> length;
                password: element.fields[1].value;
                on-random(pass) => {
                    element.fields[1].value = pass;
                }
            }
        }
    }
    VerticalLayout {
        ScrollView {
            height: Theme.app-height - 140pt;
            VerticalLayout {
                spacing: 5pt;
                RecordField {
                    height: 40pt;
                    background: Theme.primary;
                    read-only: root.read-only;
                    label: @tr("Name");
                    value: element.name;
                    edited(new_value) => {
                        element.name = new_value;
                    }
                }
                RecordField {
                    height: 40pt;
                    background: Theme.primary;
                    read-only: root.read-only;
                    label: @tr("website");
                    value: element.website;
                    edited(new_value) => {
                        element.website = new_value;
                    }
                }
                RecordField {
                    height: 40pt;
                    background: Theme.primary;
                    read-only: root.read-only;
                    label: element.fields[0].title;
                    value: element.fields[0].value;
                }
                RecordField {
                    height: 40pt;
                    background: Theme.primary;
                    read-only: root.read-only;
                    label: element.fields[1].title;
                    value: element.fields[1].value;
                    reload: true;
                    hide: true;
                    refrash => {
                        popup.show();
                        result = GeneratorLogic.request-password-gen(lowercase, upercase, nums, symbols, length);
                        element.fields[1].value = result.response;
                    }
                    edited(value) => {
                        element.fields[1].value = value;
                    }
                }
                RecordField {
                    height: 40pt;
                    background: Theme.primary;
                    read-only: root.read-only;
                    label: element.fields[2].title;
                    value: element.fields[2].value;
                }
            }
        }
        // add extra fields.
        HorizontalLayout {
            alignment: center;
            ZButton {
                text: @tr("Save");
                background: Theme.window-background-inverse;
                color: Theme.window-background;
                width: 120pt;
                height: 30pt;
                clicked => {
                    save(element);
                }
            }
        }
    }
}
