import { Theme } from "../theme.slint";

export component ZSearchInput inherits Rectangle {
    in-out property <string> value;

    border-width: 1pt;
    border-color: Theme.window-background-inverse;
    border-radius: 15pt;
    padding: 5pt;

    VerticalLayout {
        padding: 5pt;
        alignment: center;
        HorizontalLayout {
            spacing: 5pt;
            alignment: center;
            Image {
                source: @image-url("../images/search.svg");
                colorize: Theme.window-background-inverse;
                height: 20pt;
                width: 20pt;
            }
            TextInput {
                width: parent.width;
                font-family: Theme.font-family;
                font-size: Theme.font-size-regular;
                color: Theme.window-background-inverse;
                text <=> value;
                vertical-alignment: center;
            }
        }
    }
}
