import { Theme } from "../theme.slint";
import { ZButton } from "button.slint";

export component TopBar inherits Rectangle {
    in property <string> title;

    background: Theme.window-background-inverse;
    height: 40pt;
    width: Theme.app-width;

    HorizontalLayout {
        alignment: space-between;
        padding-left: 10pt;
        padding-right: 50pt;
        VerticalLayout {
            alignment: center;
            Text {
                text: root.title;
                color: Theme.primary;
                font-family: Theme.font-family;
                font-size: Theme.font-size-medium;
                font-weight: Theme.font-weight-bold;
            }
        }
        VerticalLayout {
            alignment: center;
            HorizontalLayout {
                spacing: 5pt;
                ZButton {
                    text: "add";
                    background: Theme.window-background;
                    color: Theme.window-background-inverse;
                    width: 70pt;
                    height: 30pt;
                }
                ZButton {
                    text: "Lock";
                    background: Theme.primary;
                    color: Theme.secondary;
                    width: 50pt;
                    height: 30pt;
                }
            }
        }
    }
}