import { Theme } from "../theme.slint";
import { ZButton } from "button.slint";

export component TopBar inherits Rectangle {
    in property <string> title;

    background: Theme.window-background;
    height: 40pt;
    width: Theme.app-width;

    VerticalLayout {
        HorizontalLayout {
            alignment: space-between;
            padding-left: 10pt;
            padding-right: 50pt;
            VerticalLayout {
                alignment: center;
                Text {
                    text: root.title;
                    color: Theme.primary;
                    font-family: Theme.font-family;
                    font-size: Theme.font-size-medium;
                    font-weight: Theme.font-weight-bold;
                }
            }
            VerticalLayout {
                alignment: center;
                HorizontalLayout {
                    spacing: 5pt;
                    ZButton {
                        text: "add";
                        background: Theme.window-background-inverse;
                        color: Theme.window-background;
                        width: 70pt;
                        height: 30pt;
                    }
                    ZButton {
                        text: "Lock";
                        background: Theme.primary;
                        color: Theme.secondary;
                        width: 50pt;
                        height: 30pt;
                    }
                }
            }
        }
        Rectangle {
            height: 1pt;
            background: Theme.secondary.transparentize(70%);
        }
    }
}