[package]
name = "zebra-pass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "5.0.1"
pbkdf2 = "0.12.2"
serde = { version = "1.0.188", features = ["derive"] }
sled = "0.34.7"
unicode-normalization = "0.1.22"
sha2 = { version = "0.10", default-features = false }
rand = { version = "0.8.5", features = ["small_rng"] }
ntrulp = { version = "0.1.9", features = ["ntrup1277"] }
aes = "0.8.3"
num_cpus = "1.16.0"
serde_json = "1.0.107"
hex = "0.4.3"
rand_chacha = "0.3.1"
chrono = "0.4.31"
iced = { version = "0.10.0", features = ["tokio", "image"] }
rust-i18n = "2.3.0"
dark-light = "1.0.0"
