[package]
name = "zebra-pass"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.1.1"

[build-dependencies]
slint-build = "1.1.1"
