[package]
name = "zebra-pass"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ntrulp = { version = "0.1.7", features = ["ntrup1277"] }
sled = "0.34.7"
slint = {version = "1.1.1", features = ["gettext"]}


[build-dependencies]
slint-build = "1.1.1"
