import { Theme } from "../theme.slint";
import { TopBar } from "../components/topbar.slint";
import { ZSearchInput } from "../components/search.slint";
import { ElementOfItem } from "../components/element.slint";
import { IconButton } from "../components/icon-btn.slint";
import { Logic, Element } from "../logic.slint";
import { AddElementForm } from "../components/add-record.slint";

export component ItemComponent inherits Rectangle {
    in-out property <Element> data;
    in-out property <bool> selected;

    callback clicked();

    states [
        pressed when root.selected : {
            root.background : Theme.secondary.darker(70%);
            touch.mouse-cursor: default;
        }
    ]

    touch := TouchArea {
        mouse-cursor: pointer;
        clicked => {
            clicked();
        }
    }

    HorizontalLayout {
        padding-left: 30pt;
        spacing: 16pt;
        VerticalLayout {
            alignment: center;
            Image {
                source: data.icon;
                colorize: red;
                height: 20pt;
                width: 20pt;
            }
        }
        VerticalLayout {
            alignment: center;
            Text {
                text: data.name;
                font-family: Theme.font-family;
                font-size: 10pt;
                font-weight: Theme.font-weight-bold;
                color: Theme.window-background-inverse;
            }
            Text {
                text: data.website;
                font-family: Theme.font-family;
                font-size: 8pt;
                font-weight: Theme.font-weight-regular;
                color: Theme.secondary;
                height: 10pt;
            }
        }
    }
}

export component AddEditPageManage inherits VerticalLayout {
    in property <int> index;

    TopBar {
        title: "Add Record";
    }
}
