import { IconButton } from "../components/icon-btn.slint";
import { Theme } from "../theme.slint";
import { ZComboBox } from "../components/combo-box.slint";
import { ComboBox } from "std-widgets.slint";
import { Logic } from "../logic.slint";

export component AddEditPageManage inherits VerticalLayout {
    in property <int> index : 0;

    callback close();

    VerticalLayout {
        padding: 15pt;
        padding-left: 45pt;
        padding-right: 45pt;
        width: Theme.app-width - 40pt;
        alignment: start;
        HorizontalLayout {
            alignment: space-between;
            Text {
                text: "New Record";
                font-family: Theme.font-family;
                font-size: Theme.font-size-big;
                font-weight: Theme.font-weight-bold;
                vertical-alignment: center;
            }
            IconButton {
                background: Theme.window-background-inverse;
                hover-color: Theme.secondary;
                source: @image-url("../images/close.svg");
                img-width: 30pt;
                img-height: 30pt;
                clicked => {
                    close();
                }
            }
        }
        HorizontalLayout {
            alignment: center;
            VerticalLayout {
                width: Theme.app-width  / 2;
                HorizontalLayout {
                    alignment: center;
                    ComboBox {
                        width: parent.width / 2;
                        model: Logic.records-types;
                        current-index: index;
                    }
                }
            }
        }
    }
}
