import { Theme } from "../theme.slint";
import { TopBar } from "../components/topbar.slint";
import { ZSearchInput } from "../components/search.slint";
import { ElementOfItem } from "../components/element.slint";
import { IconButton } from "../components/icon-btn.slint";
import { ItemComponent } from "../components/item-field.slint";
import { Logic, Element } from "../logic.slint";
import { Button } from "std-widgets.slint";


export component SubPageManage inherits VerticalLayout {
    private property <int> selected-index : 0;

    callback add-record();

    TopBar {
        title: "Mange";
    }
    if Logic.elements.length > 0 : HorizontalLayout {
        height: 100%;
        VerticalLayout {
            alignment: start;
            HorizontalLayout {
                padding-top: 10pt;
                padding-bottom: 10pt;
                alignment: center;
                width: 200pt;
                ZSearchInput {
                    width: 150pt;
                }
            }
            for item[index] in Logic.elements: Rectangle {
                ItemComponent {
                    preferred-height: 35pt;
                    preferred-width: 200pt;
                    data: item;
                    selected: selected-index == index;
                    clicked => {
                        selected-index = index;
                    }
                }                
            }
        }
        Rectangle {
            height: 100%;
            width: 1pt;
            background: Theme.secondary.transparentize(70%);
        }
        ElementOfItem {
            data: Logic.elements[selected-index];
            index: selected-index;
            edit => {}
            delete => {
            }
        }
    }
    if Logic.elements.length == 0 : HorizontalLayout {
        alignment: center;
        VerticalLayout {
            alignment: center;
            IconButton {
                background: Theme.window-background-inverse;
                hover-color: Theme.secondary;
                source: @image-url("../images/add.svg");
                img-width: 60pt;
                img-height: 60pt;
                clicked => {
                    add-record();
                }
            }
        }
    }
}
