import { Theme } from "../theme.slint";
import { TopBar } from "../components/topbar.slint";
import { IconWrap } from "../components/icon-wrap.slint";
import { IconButton } from "../components/icon-btn.slint";
import { ZTag } from "../components/tag.slint";
import { SpinBox , Slider, CheckBox} from "std-widgets.slint";
import { PassGenForm } from "../components/pass-gen-form.slint";
import { MnemonicGenForm } from "../components/mnemonic-gen.slint";


enum GenType {
    Password,
    Mnemonic,
    Pin
}

component SelectType inherits VerticalLayout {
    in-out property <GenType> option : GenType.Password;

    alignment: center;
    HorizontalLayout {
        spacing: 5pt;
        alignment: center;
        ZTag {
            text: "Password";
            width: 70pt;
            height: 25pt;
            color: Theme.window-background-inverse;
            color-selected: Theme.window-background;
            background-selected: Theme.info;
            background: Theme.primary;
            font-size: Theme.font-size-regular;
            selected: option == GenType.Password;
            clicked => {
                option = GenType.Password;
            }
        }
        ZTag {
            text: "Mnemonic";
            width: 70pt;
            height: 25pt;
            color: Theme.window-background-inverse;
            color-selected: Theme.window-background;
            background-selected: Theme.info;
            background: Theme.primary;
            font-size: Theme.font-size-regular;
            selected: option == GenType.Mnemonic;
            clicked => {
                option = GenType.Mnemonic;
            }
        }
        ZTag {
            text: "Pin";
            width: 70pt;
            height: 25pt;
            color: Theme.window-background-inverse;
            color-selected: Theme.window-background;
            background-selected: Theme.info;
            background: Theme.primary;
            font-size: Theme.font-size-regular;
            selected: option == GenType.Pin;
            clicked => {
                option = GenType.Pin;
            }
        }
    }
}

export component SubPagePassgen inherits VerticalLayout {
    private property <GenType> option : GenType.Mnemonic;
    private property <string> password : "dasdas3tg";

    alignment: start;

    TopBar {
        title: "Generator";
    }
    HorizontalLayout {
        alignment: center;
        height: 100%;
        VerticalLayout {
            alignment: center;
            spacing: 10pt;
            Text {
                text: "Select options Generator options";
                font-family: Theme.font-family;
                font-size: 13pt;
                horizontal-alignment: center;
            }
            SelectType {
                option <=> option;
            }
            if option == GenType.Password : PassGenForm {}
            if option == GenType.Mnemonic : MnemonicGenForm {}
        }
    }
}

