import { Theme } from "../theme.slint";
import { TopBar } from "../components/topbar.slint";
import { ZCopyIcon } from "../icons/copy.slint";
import { IconWrap } from "../components/icon-wrap.slint";
import { IconButton } from "../components/icon-btn.slint";
import { ZTag } from "../components/tag.slint";
import { SpinBox , Slider, CheckBox} from "std-widgets.slint";


enum GenType {
    Password,
    Mnemonic,
    Pin
}

component SelectType inherits VerticalLayout {
    in-out property <GenType> option : GenType.Password;

    alignment: center;
    HorizontalLayout {
        spacing: 5pt;
        alignment: center;
        ZTag {
            text: "Password";
            width: 70pt;
            height: 25pt;
            color: Theme.window-background-inverse;
            color-selected: Theme.window-background;
            background-selected: Theme.info;
            background: Theme.primary;
            font-size: Theme.font-size-regular;
            selected: option == GenType.Password;
            clicked => {
                option = GenType.Password;
            }
        }
        ZTag {
            text: "Mnemonic";
            width: 70pt;
            height: 25pt;
            color: Theme.window-background-inverse;
            color-selected: Theme.window-background;
            background-selected: Theme.info;
            background: Theme.primary;
            font-size: Theme.font-size-regular;
            selected: option == GenType.Mnemonic;
            clicked => {
                option = GenType.Mnemonic;
            }
        }
        ZTag {
            text: "Pin";
            width: 70pt;
            height: 25pt;
            color: Theme.window-background-inverse;
            color-selected: Theme.window-background;
            background-selected: Theme.info;
            background: Theme.primary;
            font-size: Theme.font-size-regular;
            selected: option == GenType.Pin;
            clicked => {
                option = GenType.Pin;
            }
        }
    }
}

export component SubPagePassgen inherits VerticalLayout {
    private property <GenType> type : GenType.Password;
    private property <string> password : "dasdas3tg";

    alignment: start;

    TopBar {
        title: "Generator";
    }
    HorizontalLayout {
        alignment: center;
        height: 100%;
        VerticalLayout {
            alignment: center;
            spacing: 5pt;
            Text {
                text: "Select options to set your password";
                font-family: Theme.font-family;
                font-size: 13pt;
                horizontal-alignment: center;
            }
            SelectType {}
            Rectangle {
                background: Theme.success;
                height: 50pt;
                width: Theme.app-width / 2 - 50pt;
                border-radius: 8pt;
                VerticalLayout {
                    alignment: center;
                    padding-left: 16pt;
                    HorizontalLayout {
                        alignment: space-between;
                        VerticalLayout {
                            alignment: center;
                            TextInput {
                                text: password;
                                read-only: true;
                                font-family: Theme.font-family;
                                font-size: Theme.font-size-medium;
                            }
                        }
                        HorizontalLayout {
                            IconButton {
                                background: Theme.window-background-inverse;
                                hover-color: Theme.secondary;
                                source: @image-url("../images/copy.svg");
                                img-width: 20pt;
                                clicked => {
                                }
                            }
                            IconButton {
                                background: Theme.window-background-inverse;
                                hover-color: Theme.secondary;
                                source: @image-url("../images/reload.svg");
                                img-width: 30pt;
                                clicked => {
                                    
                                }
                            }
                        }
                    }
                }
            }
            HorizontalLayout {
                spacing: 5pt;
                Slider {
                    min-width: 160px;
                    minimum: -100;
                    maximum: 100;
                    value: 42;
                }
                SpinBox {
                    vertical-stretch: 0;
                    value: 42;
                    width: 100pt;
                    enabled: true;
                }
            }
            HorizontalLayout {
                alignment: center;
                VerticalLayout {
                    alignment: start;
                    CheckBox {
                        text: @tr("Lowercase (a-z)");
                        checked: true;
                        enabled: true;
                    }
                    CheckBox {
                        text: @tr("Numbers (0-9)");
                        checked: true;
                        enabled: true;
                    }
                }
                VerticalLayout {
                    alignment: start;
                    CheckBox {
                        text: @tr("Uppercase (A-Z)");
                        checked: true;
                        enabled: true;
                    }
                    CheckBox {
                        text: @tr("Symbols (!-$^+)");
                        checked: true;
                        enabled: true;
                    }
                }
            }
        }
    }
}

