import { VerticalBox } from "std-widgets.slint";
import { Route } from "./route.slint";
import { Routers } from "./routers.slint";
import { Theme } from "theme.slint";
import { Logic } from "logic.slint";


component AppWindow inherits Window {
    width: Theme.app-width;
    height: Theme.app-height;
    background: Theme.window-background;

    VerticalBox {
        Route {
            route: Routers.SetupAccount;
        }
    }
}

export {
    Logic,
    AppWindow
}