import { VerticalBox } from "std-widgets.slint";
import { Route } from "./route.slint";
import { Routers } from "./routers.slint";
import { Theme } from "theme.slint";
import { Logic, KeyChainLogic } from "logic.slint";


component AppWindow inherits Window {
    in-out property<Routers> route : Routers.LangChoose;

    width: Theme.app-width;
    height: Theme.app-height;
    background: Theme.window-background;

    VerticalBox {
        Route {
            route: route;
        }
    }
}

export {
    Logic,
    KeyChainLogic,
    AppWindow
}