import { Button } from "std-widgets.slint";

import {
    LockPage,
    StartPage,
    LangChoosePage,
    MnemonicPage,
    PrivacyPage,
    LoginPage,
    SetupAccountPage,
    HomePage
} from "./pages/pages.slint";
import { Routers } from "./routers.slint";

export component Route inherits Window {
    in-out property<Routers> route: Routers.Lock;

    if(root.route == Routers.Home) : HomePage {
        continue(new-route) => {
            root.route = new-route;
        }
    }
    if(root.route == Routers.Lock) : LockPage {
        continue(new-route) => {
            root.route = new-route;
        }
    }
    if(root.route == Routers.Start) : StartPage {
        continue(new-route) => {
            root.route = new-route;
        }
    }
    if(root.route == Routers.LangChoose) : LangChoosePage {
        continue(new-route) => {
            root.route = new-route;
        }
    }
    if(root.route == Routers.Mnemonic) : MnemonicPage {
        continue(new-route) => {
            root.route = new-route;
        }
    }
    if(root.route == Routers.Login) : LoginPage {
        continue(new-route) => {
            root.route = new-route;
        }
    }
    if(root.route == Routers.Privacy) : PrivacyPage {
        continue(new-route) => {
            root.route = new-route;
        }
    }
    if(root.route == Routers.SetupAccount) : SetupAccountPage {
        continue(new-route) => {
            root.route = new-route;
        }
    }
}
