import { Button, VerticalBox } from "std-widgets.slint";

import { LockPage, StartPage, LangChoosePage } from "./pages/pages.slint";

export enum Routers {
    Lock,
    LangChoose,
    Start
}

export component Route inherits Window {
    in property<Routers> route: Routers.Lock;

    if(root.route == Routers.Lock) : LockPage {}
    if(root.route == Routers.Start) : StartPage {}
    if(root.route == Routers.LangChoose) : LangChoosePage {}
}
