import { StyleMetrics } from "std-widgets.slint";

import "fonts/Roboto-Regular.ttf";
import "fonts/Roboto-Bold.ttf";

export global Theme  {
    // brushes
    out property <brush> light: #FFFFFF;
    out property <brush> dark: #000000;

    out property <brush> primary: StyleMetrics.dark-color-scheme ? #354E73 : #007bff;
    out property <brush> secondary: StyleMetrics.dark-color-scheme ? #9E9EBE : #F2F7FD;
    out property <brush> success: StyleMetrics.dark-color-scheme ? #0A4C25 : #ABE4C2;
    out property <brush> warning: StyleMetrics.dark-color-scheme ? #C69823 :  #FEF5DF;
    out property <brush> warn: StyleMetrics.dark-color-scheme ? #C05112 :  #FFE9DD;
    out property <brush> danger: StyleMetrics.dark-color-scheme ? #A71F58 :  #FFDBEA;
    out property <brush> info: #c3fff9;

    out property <brush> window-background: StyleMetrics.dark-color-scheme ? root.dark : root.light;
    out property <brush> window-background-inverse: StyleMetrics.dark-color-scheme ? root.light : root.dark;

    // radius
    out property <length> radius-regular: 8pt;

    // sizes
    out property <length> size-small: 24px;
    out property <length> size-regular: 32px;
    out property <length> size-medium: 128px;
    out property <length> size-big: 170px;

    // spacings
    out property <length> spacing-regular: 4pt;
    out property <length> spacing-medium: 8pt;

    // typo
    out property <string> font-family: "Roboto";
    out property <length> font-size-regular: 9pt;
    out property <length> font-size-medium: 14pt;
    out property <int> font-weight-regular: 400;
    out property <int> font-weight-bold: 900;

    // UI
    out property <length> app-width: 750pt;
    out property <length> app-height: 450pt;
    out property <length> zerba-print-length: 260pt;
}